### ISSUE TITLE
Adaptar a pantalla completa

### ISSUE THREAD

**Issue by iago-suarez** [iago-suarez/mar-suarez-tfg#1]

**Comment by xoel** [comment]
Done

**Comment by iago-suarez** [comment]
Estupendo, ahora el proceso que tienes que seguir es el siguiente (previa copia de seguridad del trabajo, por supuesto):
1) Crea un fork del repositorio original:
https://help.github.com/articles/fork-a-repo/

2) Añade en ese fork que creas, lo cambios necesarios para la nueva funcionalidad que quieres incorporar (pantalla completa)

3) Una vez añadidos los cambios haz un commit con ellos

4) Utiliza el mecanismo de pull request con ellos para hacermelos llegar y que podamos revisarlos, de este modo solo entra al repositorio estable código verificado:
https://help.github.com/articles/using-pull-requests/
